---
output: html_document
---


```{r echo = FALSE, message = FALSE}
##setwd('~/github/hybridBlockSamplers')
require(ggplot2)
require(dplyr)
models <- c('pump', 'SSMind', 'SSMcor',  'litters',  'mhp',  'ice')


```

```
str(compareDF)
##'data.frame':	210 obs. of  5 variables:
## $ sampler      : chr  "RW_block" "RW_block" "RW_block" "RW_block" ...
## $ nfa          : num  NA NA NA NA NA NA NA NA NA NA ...
## $ nIter        : num  1000 1000 1000 1000 1000 1000 1000 1000 1000 1000 ...
## $ runTime      : num  0.025 0.024 0.024 0.023 0.025 ...
## $ minEfficiency: num  1185 1371 1644 1582 1159 ...

str(allEffDF)
##'data.frame':	420 obs. of  7 variables:
## $ sampler: chr  "RW_block" "RW_block" "RW_block" "RW_block" ...
## $ nfa    : num  NA NA NA NA NA NA NA NA NA NA ...
## $ nIter  : num  1000 1000 1000 1000 1000 1000 1000 1000 1000 1000 ...
## $ runTime: num  0.025 0.025 0.024 0.024 0.024 ...
## $ repNum : int  1 1 2 2 3 3 4 4 5 5 ...
## $ param  : chr  "alpha" "beta" "alpha" "beta" ...
## $ eff    : num  1793 1185 2088 1371 2687 ...
```

## Average minEfficiency 

```{r }

##modelName <- 'pump'
##modelName <- 'ice'
##par(mfrow = c(3,2))
for(modelName in models) {
    filename <- paste0('results/', modelName, 'Results.RData')
    load(filename)
    compareDF %>% filter(nIter >= 10000) -> compareDF
    compareDF %>% filter(sampler == 'AFSS_to_RW_block') -> df
    df %>% group_by(nfa, nIter) %>% summarize(mean = mean(minEfficiency)) -> tmp
    cols <- c('gray88', 'gray50', 'gray20', 'gray5')
    nfas <- c(1,2,4,8)
    xlims <- if(modelName == 'mhp') c(0, 10000) else c(0, 100000)
    yExpand <- 1.5
    ylims <- (range(tmp$mean) - mean(tmp$mean)) * yExpand + mean(tmp$mean)
    plot(0, 0, ylim = ylims, xlim = xlims, main = modelName)
    for(i in 1:4) {
        tmp %>% filter(nfa == nfas[i]) -> tmp2
        lines(tmp2$nIter, tmp2$mean, col = cols[i])
        points(tmp2$nIter, tmp2$mean, col = cols[i], pch=19)
        df %>% filter(nfa == nfas[i]) -> tmp3
        for(iter in unique(tmp3$nIter)) {
            se <- sd((tmp3 %>% filter(nIter == iter))$minEfficiency) / sqrt(10-1)
            val <- (tmp2 %>% filter(nIter==iter))$mean
            segments(iter, val-se, iter, val+se, col=cols[i])
            width <- 1000
            segments(iter-width, val-se, iter+width, val-se, col=cols[i])
            segments(iter-width, val+se, iter+width, val+se, col=cols[i])
        }
    }
    legend(x = 'bottomright', fill=cols, legend = nfas)
}




```

## Comparing Sampling Approaches

```{r }

##modelName <- 'pump'
##modelName <- 'ice'
for(modelName in models) {
    filename <- paste0('results/', modelName, 'Results.RData')
    load(filename)
    compareDF %>% filter(nIter >= 10000) -> compareDF
    compareDF %>% filter(sampler != 'AFSS_to_RW_block' | nfa == 1) -> df
    df %>% group_by(sampler, nIter) %>% summarize(mean = mean(minEfficiency)) -> tmp
    cols <- c('green', 'blue', 'red', 'pink')
    samplers <- unique(tmp$sampler)
    xlims <- if(modelName == 'mhp') c(0, 10000) else c(0, 100000)
    yExpand <- 1.5
    ylims <- (range(tmp$mean) - mean(tmp$mean)) * yExpand + mean(tmp$mean)
    plot(0, 0, ylim = ylims, xlim = xlims, main = modelName)
    for(i in 1:4) {
        tmp %>% filter(sampler == samplers[i]) -> tmp2
        lines(tmp2$nIter, tmp2$mean, col = cols[i])
        points(tmp2$nIter, tmp2$mean, col = cols[i], pch=19)
        df %>% filter(sampler == samplers[i]) -> tmp3
        for(iter in unique(tmp3$nIter)) {
            se <- sd((tmp3 %>% filter(nIter == iter))$minEfficiency) / sqrt(10-1)
            val <- (tmp2 %>% filter(nIter==iter))$mean
            segments(iter, val-se, iter, val+se, col=cols[i])
            width <- 1000
            segments(iter-width, val-se, iter+width, val-se, col=cols[i])
            segments(iter-width, val+se, iter+width, val+se, col=cols[i])
        }
    }
    legend(x = 'bottomright', fill=cols, legend = samplers)
}


```

<!--


    compareDF %>%
	group_by(sampler, nfa, nIter) %>%
	    summarize(meanEff = mean(minEfficiency), sdEff = sd(minEfficiency)/10, meanTime = mean(runTime), sdTime = sd(runTime)/10) %>%
		mutate(id = paste0(sampler, nfa)) -> df
    print(modelName)
    p <- ggplot(df, aes(x=nIter, y=meanEff, colour=id)) +
        geom_errorbar(aes(ymin=meanEff-sdEff, ymax=meanEff-sdEff), position = 'dodge') + 
            geom_line() +
                geom_point() +
                    labs(title = modelName)
    dev.new()
    print(p)

-->

